TreeViewMVC/Controllers/jsTree3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jsTree3.Models;
using Newtonsoft.Json;

namespace jsTree3.Controllers
{
    public class jsTree3Controller : Controller
    {
        public ActionResult Demo()
        {
            return View();
        }

        public ActionResult AJAXDemo()
        {
            return View();
        }
        public JsonResult GetJsTree3Data()
        {
            var root = new JsTree3Node() // Create our root node and ensure it is opened
            {
                id = Guid.NewGuid().ToString(),
                text = "Root Node",
                state = new State(true, false, false)
            };
            
            // Create a basic structure of nodes
            var children = new List<JsTree3Node>();
            for (int i = 0; i < 5; i++)
            {
                var node = JsTree3Node.NewNode(Guid.NewGuid().ToString());
                node.state = new State(IsPrime(i), false, false);

                for (int y = 0; y < 5; y++)
                {
                    node.children.Add(JsTree3Node.NewNode(Guid.NewGuid().ToString()));
                }

                children.Add(node);
            }

            // Add the sturcture to the root nodes children property
            root.children = children;
            
            // Return the object as JSON
            return Json(root, JsonRequestBehavior.AllowGet);
        }

        static bool IsPrime(int n)
        {
            if (n > 1)
            {
                return Enumerable.Range(1, n).Where(x => n % x == 0)
                                 .SequenceEqual(new[] { 1, n });
            }

            return false;
        }
    }
}

TreeViewMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Categories", "TreeView", "Home")</li>
                    <li>@Html.ActionLink("Levels", "TreeViewLevel", "Home")</li>
                    <li>@Html.ActionLink("TreeViewVehicle", "TreeViewVehicle", "Home")</li>
                    <li>@Html.ActionLink("Demo", "Demo", "jsTree3")</li>
                    <li>@Html.ActionLink("AJAXDemo", "AJAXDemo", "jsTree3")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TreeViewMVC/Views/Shared/_jsTreeDemo.cshtml
@{
    Layout = null;

    ViewBag.Title = string.Format("jsTree 3.1.1 - {0}", ViewBag.Title);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="http://static.jstree.com/3.0.0-beta5/assets/bootstrap/css/bootstrap.css" />
    <link href="~/Content/jsTree/docs.css" rel="stylesheet" />
    <link href="~/Content/jsTree/themes/default/style.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jsTree3/jstree.js"></script>

</head>
<body>
    <header id="head">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12">
                    <h1 id="logo"><a href="http://jstree.com">jsTree - jQuery tree plugin<span>3.1.1</span></a></h1>
                </div>
                <div class="col-md-6 col-sm-8">
                    <nav>
                        <ul class="nav nav-pills" id="menu"><li class="active"><li class="active"><a href="/jsTree3/Demo"> @ViewBag.Title</a></ul>
</nav>
                </div>
                <div class="col-md-3 col-sm-4">

                </div>
            </div>
        </div>
    </header>
    <div>
        <div class="container" id="content">
            <div class="row page" id="docs" style="display:block;">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>